disabled_rules:
  - trailing_whitespace
  - function_body_length
  - line_length
  - orphaned_doc_comment
  - nesting

opt_in_rules:
  - let_var_whitespace
  
excluded:
  - Mogakco/Application

file_length:
  warning: 400
  error: 500

type_name:
  min_length: 2
  excluded:
    - T
    - U
    - R
    
identifier_name:
  min_length: 2
  excluded:
    - to
    - from
    - at

force_cast: warning
